import { PrismaClient } from "@prisma/client";
const p = new PrismaClient();
async function main() {
  console.log("Seeding...");
  await p.notification.deleteMany(); await p.auditLog.deleteMany(); await p.approval.deleteMany(); await p.anomaly.deleteMany(); await p.objection.deleteMany(); await p.utilizationCertificate.deleteMany(); await p.expense.deleteMany(); await p.budgetHead.deleteMany(); await p.milestone.deleteMany(); await p.grant.deleteMany(); await p.user.deleteMany();
  const pi = await p.user.create({data:{id:"u-pi",name:"Dr. Arjun Sharma",email:"arjun.sharma@university.edu",password:"demo1234",role:"PI",department:"Biotechnology",designation:"Associate Professor"}});
  const fin = await p.user.create({data:{id:"u-fin",name:"Rohit Mehta",email:"rohit.mehta@university.edu",password:"demo1234",role:"FINANCE",department:"Accounts",designation:"Senior Finance Officer"}});
  const adm = await p.user.create({data:{id:"u-adm",name:"Dr. Meera Iyer",email:"meera.iyer@university.edu",password:"demo1234",role:"ADMIN",department:"Research Office",designation:"Dean — Research"}});
  const aud = await p.user.create({data:{id:"u-aud",name:"S.K. Verma",email:"sk.verma@university.edu",password:"demo1234",role:"AUDITOR",department:"Internal Audit",designation:"Senior Auditor"}});
  const pi2 = await p.user.create({data:{id:"u-pi2",name:"Dr. Priya Verma",email:"priya.verma@university.edu",password:"demo1234",role:"PI",department:"Computer Science",designation:"Professor"}});
  const pi3 = await p.user.create({data:{id:"u-pi3",name:"Dr. Kumar Iyer",email:"kumar.iyer@university.edu",password:"demo1234",role:"PI",department:"Chemistry",designation:"Assistant Professor"}});
  const g1 = await p.grant.create({data:{id:"GR-DST-2401",grantCode:"GR-DST-2401",title:"CRISPR-based diagnostics for AMR pathogens",agency:"DST",sanctionedAmount:8450000,spentAmount:5620000,startDate:new Date("2024-04-01"),endDate:new Date("2027-03-31"),status:"ACTIVE",piId:pi.id,ucDueDate:new Date("2026-09-30")}});
  const g2 = await p.grant.create({data:{id:"GR-SERB-2318",grantCode:"GR-SERB-2318",title:"Metabolic engineering of microbial hosts",agency:"SERB",sanctionedAmount:6200000,spentAmount:4180000,startDate:new Date("2023-10-01"),endDate:new Date("2026-09-30"),status:"ACTIVE",piId:pi.id,ucDueDate:new Date("2026-08-31")}});
  const g3 = await p.grant.create({data:{id:"GR-ICMR-2512",grantCode:"GR-ICMR-2512",title:"Point-of-care TB assay validation",agency:"ICMR",sanctionedAmount:9850000,spentAmount:6900000,startDate:new Date("2025-01-15"),endDate:new Date("2028-01-14"),status:"ACTIVE",piId:pi.id,ucDueDate:new Date("2026-10-15")}});
  const g4 = await p.grant.create({data:{id:"GR-UGC-2209",grantCode:"GR-UGC-2209",title:"Computational genomics core facility",agency:"UGC",sanctionedAmount:4120000,spentAmount:4010000,startDate:new Date("2022-07-01"),endDate:new Date("2026-06-30"),status:"ACTIVE",piId:pi2.id,ucDueDate:new Date("2026-08-20")}});
  const g5 = await p.grant.create({data:{id:"GR-CSIR-2411",grantCode:"GR-CSIR-2411",title:"Green catalysis for pharma intermediates",agency:"CSIR",sanctionedAmount:5300000,spentAmount:2100000,startDate:new Date("2024-08-01"),endDate:new Date("2027-07-31"),status:"ACTIVE",piId:pi3.id,ucDueDate:new Date("2026-11-01")}});
  const g6 = await p.grant.create({data:{id:"GR-DST-2390",grantCode:"GR-DST-2390",title:"National biorepository network node",agency:"DST",sanctionedAmount:15200000,spentAmount:9800000,startDate:new Date("2023-04-01"),endDate:new Date("2026-03-31"),status:"ACTIVE",piId:pi2.id,ucDueDate:new Date("2026-09-01")}});
  const bh1=await p.budgetHead.create({data:{id:"bh-1",name:"Equipment",category:"EQUIPMENT",allocatedAmount:3500000,spentAmount:2100000,grantId:g1.id}});
  const bh2=await p.budgetHead.create({data:{id:"bh-2",name:"Consumables",category:"CONSUMABLES",allocatedAmount:1800000,spentAmount:1200000,grantId:g1.id}});
  const bh3=await p.budgetHead.create({data:{id:"bh-3",name:"Travel",category:"TRAVEL",allocatedAmount:600000,spentAmount:180000,grantId:g1.id}});
  const bh4=await p.budgetHead.create({data:{id:"bh-4",name:"Contingency",category:"CONTINGENCY",allocatedAmount:400000,spentAmount:140000,grantId:g1.id}});
  const bh5=await p.budgetHead.create({data:{id:"bh-5",name:"Manpower",category:"MANPOWER",allocatedAmount:1500000,spentAmount:1500000,grantId:g1.id}});
  const bh6=await p.budgetHead.create({data:{id:"bh-6",name:"Overhead",category:"OVERHEAD",allocatedAmount:650000,spentAmount:500000,grantId:g1.id}});
  const bh7=await p.budgetHead.create({data:{id:"bh-7",name:"Equipment",category:"EQUIPMENT",allocatedAmount:2200000,spentAmount:1600000,grantId:g2.id}});
  const bh8=await p.budgetHead.create({data:{id:"bh-8",name:"Consumables",category:"CONSUMABLES",allocatedAmount:1800000,spentAmount:1100000,grantId:g2.id}});
  const bh9=await p.budgetHead.create({data:{id:"bh-9",name:"Travel",category:"TRAVEL",allocatedAmount:500000,spentAmount:220000,grantId:g2.id}});
  const bh10=await p.budgetHead.create({data:{id:"bh-10",name:"Equipment",category:"EQUIPMENT",allocatedAmount:4000000,spentAmount:2800000,grantId:g3.id}});
  const bh11=await p.budgetHead.create({data:{id:"bh-11",name:"Consumables",category:"CONSUMABLES",allocatedAmount:2500000,spentAmount:1900000,grantId:g3.id}});
  const bh12=await p.budgetHead.create({data:{id:"bh-12",name:"Equipment",category:"EQUIPMENT",allocatedAmount:2300000,spentAmount:2200000,grantId:g4.id}});
  const bh13=await p.budgetHead.create({data:{id:"bh-13",name:"Consumables",category:"CONSUMABLES",allocatedAmount:1800000,spentAmount:700000,grantId:g5.id}});
  const e1=await p.expense.create({data:{id:"EXP-1042",amount:428500,date:new Date("2026-07-12"),vendorName:"Thermo Fisher Scientific",invoiceNumber:"TFS/DEL/88421",gstNumber:"07AABCT3518Q1Z4",description:"QuantStudio reagents",status:"SUBMITTED",complianceStatus:"COMPLIANT",budgetHeadId:bh1.id,grantId:g1.id,submittedById:pi.id}});
  const e2=await p.expense.create({data:{id:"EXP-1041",amount:48200,date:new Date("2026-07-08"),vendorName:"MakeMyTrip Business",invoiceNumber:"MMT-B2B-9921",gstNumber:"07AADCM5146R1ZV",description:"Conference travel Delhi-Pune",status:"APPROVED",complianceStatus:"WARNING",budgetHeadId:bh3.id,grantId:g1.id,submittedById:pi.id}});
  const e3=await p.expense.create({data:{id:"EXP-1039",amount:91200,date:new Date("2026-07-02"),vendorName:"Sigma-Aldrich",invoiceNumber:"SA-IN-12011",gstNumber:"27AABCS1234A1Z9",description:"Culture media lot",status:"APPROVED",complianceStatus:"COMPLIANT",budgetHeadId:bh8.id,grantId:g2.id,submittedById:pi.id}});
  const e4=await p.expense.create({data:{id:"EXP-1038",amount:18500,date:new Date("2026-06-28"),vendorName:"Office Depot India",invoiceNumber:"ODI-44190",gstNumber:"07AAACO0000A1Z1",description:"Stationery - GSTIN checksum fail",status:"CORRECTION_REQUESTED",complianceStatus:"WARNING",budgetHeadId:bh4.id,grantId:g1.id,submittedById:pi.id}});
  const e5=await p.expense.create({data:{id:"EXP-1035",amount:428500,date:new Date("2026-07-14"),vendorName:"Thermo Fisher Scientific",invoiceNumber:"TFS/DEL/88421",gstNumber:"07AABCT3518Q1Z4",description:"Duplicate of EXP-1042",status:"SUBMITTED",complianceStatus:"NON_COMPLIANT",budgetHeadId:bh1.id,grantId:g1.id,submittedById:pi.id}});
  const e6=await p.expense.create({data:{id:"EXP-1028",amount:186000,date:new Date("2026-06-11"),vendorName:"Dell Technologies",invoiceNumber:"DELL-IN-7721",gstNumber:"29AABCD1234E1Z5",description:"Workstation",status:"APPROVED",complianceStatus:"COMPLIANT",budgetHeadId:bh12.id,grantId:g4.id,submittedById:pi2.id}});
  const e7=await p.expense.create({data:{id:"EXP-1021",amount:12400,date:new Date("2026-05-22"),vendorName:"IRCTC Tourism",invoiceNumber:"IR-88921",gstNumber:"07AAACI0000A1Z8",description:"Unapproved personal travel",status:"REJECTED",complianceStatus:"WARNING",budgetHeadId:bh9.id,grantId:g2.id,submittedById:pi3.id}});
  const e8=await p.expense.create({data:{id:"EXP-1019",amount:265000,date:new Date("2026-07-01"),vendorName:"Qiagen India",invoiceNumber:"QI-77210",gstNumber:"07AAACQ1234A1Z8",description:"Extraction kits",status:"SUBMITTED",complianceStatus:"COMPLIANT",budgetHeadId:bh13.id,grantId:g5.id,submittedById:pi2.id}});
  await p.anomaly.create({data:{id:"AN-01",severity:"HIGH",reason:"Duplicate invoice TFS/DEL/88421 (EXP-1042 & EXP-1035)",expenseId:e5.id}});
  await p.anomaly.create({data:{id:"AN-02",severity:"MEDIUM",reason:"Travel claim exceeds GFR metro DA cap",expenseId:e2.id}});
  await p.anomaly.create({data:{id:"AN-03",severity:"HIGH",reason:"Vendor GSTIN checksum failed",expenseId:e4.id}});
  await p.approval.create({data:{action:"APPROVED",expenseId:e2.id,approverId:fin.id}});
  await p.approval.create({data:{action:"APPROVED",expenseId:e3.id,approverId:fin.id}});
  await p.approval.create({data:{action:"REJECTED",expenseId:e7.id,approverId:fin.id,reason:"Personal travel not approved"}});
  await p.milestone.create({data:{id:"m1",title:"Assay protocol locked",dueDate:new Date("2026-09-15"),status:"IN_PROGRESS",grantId:g1.id}});
  await p.milestone.create({data:{id:"m2",title:"Field validation n=200",dueDate:new Date("2026-12-01"),status:"PENDING",grantId:g1.id}});
  await p.milestone.create({data:{id:"m3",title:"Strain library deposit",dueDate:new Date("2026-08-20"),status:"DELAYED",grantId:g2.id}});
  await p.objection.create({data:{id:"ob-1",title:"Duplicate equipment invoice",status:"OPEN",note:"Recommend recovery of 4,28,500",grantId:g1.id}});
  await p.objection.create({data:{id:"ob-2",title:"Missing asset tag on PCR",status:"OPEN",note:"GFR asset register incomplete",grantId:g1.id}});
  await p.notification.create({data:{id:"n1",userId:pi.id,title:"UC due in 41 days",message:"DST CRISPR grant UC for FY 2025-26 is due 30 Sep 2026.",type:"UC_DUE"}});
  await p.notification.create({data:{id:"n2",userId:pi.id,title:"Expense pending approval",message:"Thermo Fisher invoice 4,28,500 awaits finance verification.",type:"APPROVAL_PENDING"}});
  await p.notification.create({data:{id:"n3",userId:fin.id,title:"Anomaly flagged",message:"Duplicate bill detected on GR-DST-2401.",type:"ANOMALY_DETECTED"}});
  await p.notification.create({data:{id:"n4",userId:adm.id,title:"NIRF window",message:"Research metrics snapshot ready for review.",type:"GENERAL"}});
  await p.auditLog.create({data:{id:"al-1",action:"SEED",entityType:"System",entityId:"init",userId:adm.id,metadata:{note:"Database seeded"}}});
  console.log("✅ Seed complete!");
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>p.$disconnect());
