import PDFDocument from "pdfkit";

export function ucPdfBuffer({ grant, uc, heads }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(14).text("GFR 12 – A", { align: "center" });
    doc.fontSize(10).text("FORM OF UTILIZATION CERTIFICATE", { align: "center" });
    doc.moveDown();
    doc.fontSize(9).text(`Certificate No. ${uc.id}    FY ${uc.financialYear}    ${uc.period}`);
    doc.moveDown();
    doc.fontSize(10).text(
      `Certified that out of Rs. ${Number(grant.amount).toLocaleString("en-IN")} sanctioned in favour of ${grant.pi} under ${grant.id} for "${grant.title}", a sum of Rs. ${Number(uc.totalUtilized).toLocaleString("en-IN")} has been utilized and the balance of Rs. ${Number(uc.balanceAmount).toLocaleString("en-IN")} remains unutilized.`
    );
    doc.moveDown();
    doc.fontSize(10).text("Statement of Expenditure", { underline: true });
    doc.moveDown(0.5);
    (heads || []).forEach((h) => {
      doc.fontSize(9).text(`${h.name}: sanctioned Rs. ${Number(h.allocated).toLocaleString("en-IN")}  utilized Rs. ${Number(h.spent).toLocaleString("en-IN")}`);
    });
    doc.moveDown();
    doc.fontSize(9).text("Certified that the conditions of the grant have been fulfilled / are being fulfilled.");
    doc.moveDown(2);
    doc.text("________________________                    ________________________");
    doc.text("Signature of PI                             Finance Officer / Registrar");
    doc.moveDown();
    doc.fontSize(8).fillColor("#555").text("Generated by ShodhFund (demo). Not a legally signed UC.");
    doc.end();
  });
}
